resources:
  - kind: folder
    selector:
      query: 'true'
      folders:
        - path: resources/*
          repos:
            - ios_project
    port:
      entity:
        mappings:
          identifier: ".folder.name"
          blueprint: '"folder"'
          properties:
            link: '"abc"'
