resources:
  - kind: folder
    selector:
      query: 'true'
      folders:
        - path: SpaceInvaders/*
          repos:
            - ios_project
    port:
      entity:
        mappings:
          identifier: .folderName
          blueprint: '"folder"'
          properties:
            link: "'abc'"
